### ISSUE TITLE
Dimension mismatch while testing

### ISSUE THREAD

**Issue by Niharikajo** [18kiran12/Yformer-Time-Series-Forecasting#1]
Hello Kiran,

Thank you for releasing the code, 
I had a few issues while trying to run the code,

I am trying to do a univariate prediction. I have considered batch_size as 32, seq_length, and label_length as 48.

1.  For pred_length greater than 131 I'm unable to get the test predictions, The output dimension of the model for pred_length more than 131 is always [32, 131, 1]. So there is a dimension mismatch between the trues and preds while testing.

2.  The final preds and trues we get after testing are normalized, How to denormalize these values?
     I was able to denormalize the test data using the inverse_transform function.

Please let me know the fix to the first issue.

Best regards
Niharika

**Comment by 18kiran12** [comment]
Hello Niharikajo,

Thanks for reaching out to us and finding interest in our work.
Unfortunately, I was unable to reproduce the issue.
Either way, I have updated the code to the latest version and it would be great if you could give it one more shot 
and let me know if the error still exists.

Regards,
Kiran

**Comment by 18kiran12** [comment]
Hello Niharikajo,

Hope the issue is solved. Closing the issue as the issue is stale.
