### ISSUE TITLE
future predictor usage

### ISSUE THREAD

**Issue by koszpe** [18kiran12/Yformer-Time-Series-Forecasting#2]
First of all, thanks for your great work!
I'm trying to understand your code, and I can't identify the usage of future predictors. If I understand the paper correctly, the future predictors are features about the predicted time horizon (T+1 ... T+ tau). You have a future encoder, which encode the x_dec:
https://github.com/18kiran12/Yformer-Time-Series-Forecasting/blob/65783ab25ad350d55bc12938630565727eb03b2b/models/model.py#L294

it is called dec_inp here:
https://github.com/18kiran12/Yformer-Time-Series-Forecasting/blob/65783ab25ad350d55bc12938630565727eb03b2b/exp/exp_informer.py#L208

The dec_inp is initialized to zero, and remain zero if not use_decoder_tokens:
https://github.com/18kiran12/Yformer-Time-Series-Forecasting/blob/65783ab25ad350d55bc12938630565727eb03b2b/exp/exp_informer.py#L203
otherwise the first part of the batch_y is concatenated.

The first part of the batch_y however contains info about the past when use_decoder_tokens is true:
https://github.com/18kiran12/Yformer-Time-Series-Forecasting/blob/65783ab25ad350d55bc12938630565727eb03b2b/data/data_loader.py#L102

Am I misunderstanding something?

**Comment by 18kiran12** [comment]
Hi,

Thanks a lot for your interest in our work.
We always set the use_decoder_tokens parameter to False and therefore we do not work with the past data in batch_y as shown in the below script from data_loader.py.

        if not self.use_decoder_tokens:
            # decoder without tokens
            r_begin = s_end
            r_end = r_begin + self.pred_len

You are right that the dec_inp is basically just zeros (tokens) and one could avoid using it. We tried to share the future and past encoder and required the inputs to be of the same shape for one of the experiments and kept the zeros for dec_inp similar to the Informer paper. However, the future predictors that we try to encode are the time step features like day, month etc. These come from the 'batch_y_mark' variable.

**Comment by koszpe** [comment]
Thanks for the answer! I want to use other future predictors next to the time step feature. Do you think the dec_inp is applicable for that purpose?

**Comment by 18kiran12** [comment]
yes, if you already have future information available you could use the dec_inp for this purpose.

**Comment by koszpe** [comment]
Thanks a lot!
