### ISSUE TITLE
Test train split 

### ISSUE THREAD

**Issue by Niharikajo** [18kiran12/Yformer-Time-Series-Forecasting#3]
Hello,

I had a doubt in the data processing step

1. In ETTm2 dataset in data/data_loader to  split the dataset we use the following code to calculate border and then calculate the number of train and test points.
Can you explain this line of code? Is any formula used here ? 

`border1s = [0, 12*30*24*4 - self.seq_len, 12*30*24*4+4*30*24*4 - self.seq_len]
        border2s = [12*30*24*4, 12*30*24*4+4*30*24*4, 12*30*24*4+8*30*24*4]`

2. seq_len is calculated as 24 * 4 * 4 how is this calculated? What does it signify?

Please let me know

Thank you
Niharika

**Comment by 18kiran12** [comment]
Hello,

Thanks for your interest in our work.

1. The code basically stores the train, val and test split from the original Informer baseline.  For example, here train split is from border1s[0] - border2s[0], validation is from border1s[1] - border2s[1] and similarly for the test set. The values 12*30*24*4 indicate 12 months of data in a 15 min frequency.
2. As mentioned before, 24*4*4 implies 15 min interval time steps for 24 hours and 4 days

Regards,
Kiran

**Comment by Niharikajo** [comment]
Thank you for the answer
It was very helpful
