### ISSUE TITLE
Notation used 

### ISSUE THREAD

**Issue by Niharikajo** [18kiran12/Yformer-Time-Series-Forecasting#6]
Hello, 

While going through the paper I had a doubt regarding the notations used in the paper and code

As per the notations in the paper ( fig 1 in page 2)
 x - past predictor
 y - past target 
x’ - future predictor
y’ - future target  

While going through the code 
in dataloader.py, data is divided into quadruples ( past predictor, past target, future predictor, future target)  
here,
seq_x - past target
seq_y - future target
seq_x_mark - past predictor
seq_y_mark - future predictor

Here past values are denoted by x and future values are denoted by y

Can you please let me know if this is correct

Thank you
Niharika Joshi

**Comment by 18kiran12** [comment]
Hi Niharika,

Thanks for your interest in our work. 
yes, your interpretation of the code is correct. We merely adopted the naming scheme for the code from the Informer framework. 

Regards,
Kiran
